version: '3'
services:
  online-cinema.api:
    image: ghcr.io/itsaln/online-cinema-server/online-cinema:develop
    container_name: online-cinema
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./.env:/opt/app/.env